name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            preset: linux-gcc
            compiler: gcc
          - os: windows-latest
            preset: windows
            compiler: msvc
          - os: macos-latest
            preset: macos
            compiler: clang

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.20'

    - name: Configure CMake
      run: cmake --preset=${{ matrix.preset }}

    - name: Build
      run: cmake --build build/${{ matrix.preset }} --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: build/${{ matrix.preset }}
      run: ctest --output-on-failure --build-config ${{ env.BUILD_TYPE }}

    - name: Run demo
      working-directory: build/${{ matrix.preset }}
      run: ./R3_demo${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  mathematical-precision:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.20'

    - name: Install high-precision libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libmpfr-dev libgmp-dev

    - name: Configure CMake with precision tests
      run: cmake --preset=debug -DENABLE_PRECISION_TESTS=ON

    - name: Build precision tests
      run: cmake --build build/debug --target precision-tests

    - name: Run precision validation
      run: |
        cd build/debug
        ./precision-tests

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.20'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy cppcheck

    - name: Configure CMake with static analysis
      run: cmake --preset=debug -DENABLE_STATIC_ANALYSIS=ON

    - name: Build with static analysis
      run: cmake --build build/debug

    - name: Run static analysis
      run: |
        cd build/debug
        make clang-tidy
        make cppcheck
